//> using dep "org.scalameta::munit:1.1.1"
//> using scala "2.13"

//> using publish.name "eztime"
//> using publish.organization "xyz.matthieucourt"
//> using publish.version "0.0.3"
//> using publish.url "https://github.com/mattlianje/eztime"
//> using publish.vcs "github:mattlianje/eztime"
//> using publish.license "GPL-3.0"
//> using publish.developer "mattlianje|Matthieu Court|https://github.com/mattlianje"
//> using publish.gpgKey "EBD031A099D734786A3D035A58C96F93A67A96E9"
